import { db,rawEnv,hash } from '@/lib/server';
import { dayKey,dateLabel } from '@/lib/models';
import {localTime,deadlineJobKey,needsDeadline,morningText,type ReminderTask} from '@/lib/reminders';
import {z} from 'zod';
export async function POST(req:Request){const secret=rawEnv().TELEGRAM_SERVICE_SECRET;const supplied=req.headers.get('authorization')?.replace(/^Bearer /,'');if(!secret||!supplied||await hash(secret)!==await hash(supplied))return Response.json({error:'Forbidden'},{status:403});try{const body=z.object({action:z.string(),username:z.string().optional()}).passthrough().parse(await req.json());const now=new Date();const stamp=now.toISOString();if(body.action==='heartbeat'){if(!z.string().regex(/^[a-zA-Z0-9_]{5,32}$/).safeParse(body.username).success)return Response.json({error:'Invalid username'},{status:400});await db().prepare('INSERT INTO service_state (id,username,heartbeat) VALUES (?,?,?) ON CONFLICT(id) DO UPDATE SET username=excluded.username,heartbeat=excluded.heartbeat').bind('telegram',body.username,now.getTime()).run();return Response.json({ok:true});}
if(body.action==='confirm'){const parsed=z.object({code:z.string().regex(/^[a-f0-9]{48}$/),chatId:z.string().regex(/^\d{1,20}$/),name:z.string().max(200)}).safeParse(body);if(!parsed.success)return Response.json({ok:false});const {code,chatId,name}=parsed.data;const link=await db().prepare('SELECT owner FROM auth_links WHERE hash=? AND expires_at>? AND used=0 AND confirmed=0').bind(await hash(code),now.getTime()).first<{owner:string}>();if(!link)return Response.json({ok:false,message:'Посилання застаріло. Створіть нове на сайті.'});const p=await db().prepare('SELECT telegram_id FROM preferences WHERE owner=?').bind(link.owner).first<{telegram_id:string|null}>();if(p?.telegram_id && p.telegram_id!==chatId)return Response.json({ok:false,message:'Підтвердіть вхід із підключеного Telegram-акаунта.'});const duplicate=await db().prepare('SELECT owner FROM preferences WHERE telegram_id=? AND owner<>?').bind(chatId,link.owner).first();if(duplicate)return Response.json({ok:false,message:'Цей Telegram уже підключений до іншого простору.'});await db().batch([db().prepare('INSERT INTO preferences (owner,telegram_id,telegram_name) VALUES (?,?,?) ON CONFLICT(owner) DO UPDATE SET telegram_id=excluded.telegram_id,telegram_name=excluded.telegram_name').bind(link.owner,chatId,name),db().prepare('UPDATE auth_links SET confirmed=1 WHERE hash=? AND expires_at>?').bind(await hash(code),now.getTime())]);return Response.json({ok:true,message:'✅ Telegram підключено. Поверніться на сайт, щоб завершити вхід.'});}
if(body.action==='tick'){const users=(await db().prepare('SELECT * FROM preferences WHERE telegram_id IS NOT NULL').all<{owner:string;telegram_id:string;timezone:string;morning_time:string;morning_enabled:number;deadline_enabled:number}>()).results;for(const p of users){const tasks=(await db().prepare("SELECT id,title,due_at,reminder_version FROM records WHERE owner=? AND kind='task' AND status<>'done' AND due_at IS NOT NULL ORDER BY due_at").bind(p.owner).all<ReminderTask>()).results;const jobs:{id:string;message:string;taskId?:string;deadline?:string;version?:number}[]=[];if(p.morning_enabled && localTime(now,p.timezone)>=p.morning_time && Number(localTime(now,p.timezone).slice(0,2))*60+Number(localTime(now,p.timezone).slice(3)) < Number(p.morning_time.slice(0,2))*60+Number(p.morning_time.slice(3))+60 && tasks.length){jobs.push({id:`morning:${p.owner}:${dayKey(now,p.timezone)}`,message:morningText(tasks,now,p.timezone)});}if(p.deadline_enabled){for(const t of tasks.filter(t=>needsDeadline(t,now)))jobs.push({id:deadlineJobKey(t),taskId:t.id,deadline:t.due_at,version:t.reminder_version,message:`⏰ Наближається дедлайн\n\n${t.title}\n${dateLabel(t.due_at,p.timezone)}\n\nЗалишилося ${Math.ceil((Date.parse(t.due_at)-now.getTime())/60000)} хв.`});}if(jobs.length)await db().batch(jobs.map(j=>db().prepare('INSERT OR IGNORE INTO outbox (id,owner,chat_id,message,status,created_at,updated_at,task_id,deadline,reminder_version) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(j.id,p.owner,p.telegram_id,j.message.slice(0,4000),'pending',stamp,stamp,j.taskId??null,j.deadline??null,j.version??null)));}
await db().prepare("UPDATE outbox SET status='cancelled',updated_at=? WHERE status='pending' AND task_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM records WHERE records.id=outbox.task_id AND records.owner=outbox.owner AND records.status<>'done' AND records.due_at=outbox.deadline AND records.reminder_version=outbox.reminder_version AND records.due_at>?)").bind(stamp,stamp).run();
// Never re-claim sending/unknown rows: Telegram sendMessage has no idempotency key.
await db().prepare("UPDATE outbox SET status='unknown',error='Delivery uncertain after service interruption',updated_at=? WHERE status='sending' AND updated_at<?").bind(stamp,new Date(now.getTime()-120000).toISOString()).run();const jobs=(await db().prepare("UPDATE outbox SET status='sending',updated_at=? WHERE id IN (SELECT id FROM outbox WHERE status='pending' ORDER BY created_at LIMIT 20) RETURNING id,chat_id,message").bind(stamp).all()).results;return Response.json({jobs});}
if(body.action==='ack'){const parsed=z.object({id:z.string().max(300),status:z.enum(['sent','failed','unknown']),error:z.string().max(300).optional()}).safeParse(body);if(!parsed.success)return Response.json({error:'Invalid acknowledgement'},{status:400});await db().prepare("UPDATE outbox SET status=?,error=?,updated_at=? WHERE id=? AND status='sending'").bind(parsed.data.status,parsed.data.error??null,stamp,parsed.data.id).run();return Response.json({ok:true});}if(body.action==='health')return Response.json({ok:true});return Response.json({error:'Unknown action'},{status:400});}catch{console.error('Telegram service operation failed');return Response.json({error:'Service operation failed'},{status:503});}}
