import { env } from 'cloudflare:workers';
import { cookies } from 'next/headers';
import { getChatGPTUser } from '@/app/chatgpt-auth';
import type { Entry, Preferences, WorkspaceData } from './models';
export function db(){ if(!env.DB) throw new Error('База даних тимчасово недоступна. Спробуйте ще раз.'); return env.DB; }
export function rawEnv(){ return env as Cloudflare.Env & {TELEGRAM_SERVICE_SECRET?:string}; }
export async function hash(value:string){const data=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return Array.from(new Uint8Array(data),b=>b.toString(16).padStart(2,'0')).join('');}
export function nonce(){return crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-','');}
export async function owner(){ const user=await getChatGPTUser(); if(!user) throw new Error('UNAUTHORIZED'); return user; }
export async function preferences(id:string):Promise<Preferences>{const row=await db().prepare('SELECT * FROM preferences WHERE owner = ?').bind(id).first<Record<string,unknown>>();return {timezone:String(row?.timezone??'Europe/Berlin'),morningTime:String(row?.morning_time??'08:00'),morningEnabled:row?.morning_enabled!==0,deadlineEnabled:row?.deadline_enabled!==0,telegramId:row?.telegram_id ? String(row.telegram_id):null,telegramName:row?.telegram_name?String(row.telegram_name):null,telegramRequired:row?.telegram_required===1};}
export async function hasSession(id:string){const cookie=(await cookies()).get('focus_telegram_session')?.value;if(!cookie)return false;return !!await db().prepare('SELECT hash FROM sessions WHERE hash = ? AND owner = ? AND expires_at > ?').bind(await hash(cookie),id,Date.now()).first();}
export async function authorized(){const user=await owner();const p=await preferences(user.userId);if(p.telegramRequired && !(await hasSession(user.userId)))throw new Error('TELEGRAM_REQUIRED');return user;}
export function checkOrigin(req:Request){if(req.headers.get('origin')!==new URL(req.url).origin)throw new Error('FORBIDDEN');}
export function failure(err:unknown){const msg=err instanceof Error?err.message:'Помилка сервера';const status=msg==='UNAUTHORIZED'?401:msg==='FORBIDDEN'?403:msg==='TELEGRAM_REQUIRED'?423:msg.startsWith('VALIDATION:')?400:503;if(status===503)console.error('Workspace operation failed');return Response.json({error:status===503?'Не вдалося виконати дію. Ваші зміни залишилися в редакторі. Спробуйте ще раз.':msg},{status});}
export function toEntry(row:Record<string,unknown>):Entry{return {id:String(row.id),kind:row.kind as Entry['kind'],title:String(row.title),topic:String(row.topic),blocks:JSON.parse(String(row.blocks)),status:row.status as Entry['status'],priority:row.priority as Entry['priority'],dueAt:row.due_at?String(row.due_at):null,createdAt:String(row.created_at),updatedAt:String(row.updated_at)};}
export async function workspace():Promise<WorkspaceData>{const u=await owner();const p=await preferences(u.userId);const gate=p.telegramRequired&&!(await hasSession(u.userId));const state=await db().prepare('SELECT * FROM service_state WHERE id = ?').bind('telegram').first<{username:string;heartbeat:number}>();const rows=gate?[]:(await db().prepare('SELECT * FROM records WHERE owner = ? ORDER BY updated_at DESC').bind(u.userId).all<Record<string,unknown>>()).results;return {entries:rows.map(toEntry),preferences:p,telegram:{configured:!!rawEnv().TELEGRAM_SERVICE_SECRET,username:state?.username??null,online:!!state&&Date.now()-state.heartbeat<90000,lastSeen:state?.heartbeat??0,gate},displayName:u.fullName??'Мій простір'};}
