import ts from 'typescript';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
const translationsUrl=pathToFileURL(process.cwd()+'/lib/translations.mjs').href;
const compile=p=>ts.transpileModule(readFileSync(p,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText;
const i18nUrl='data:text/javascript;base64,'+Buffer.from(compile('lib/i18n.ts').replace("'./translations.mjs'",JSON.stringify(translationsUrl))).toString('base64');
const modelsUrl='data:text/javascript;base64,'+Buffer.from(compile('lib/models.ts').replace("'./i18n'",JSON.stringify(i18nUrl))).toString('base64');
const models=await import(modelsUrl);
const recurrenceSource=compile('lib/recurrence.ts').replace("'./i18n'",JSON.stringify(i18nUrl)).replace("'./models'",JSON.stringify(modelsUrl));
const recurrenceUrl='data:text/javascript;base64,'+Buffer.from(recurrenceSource).toString('base64');
const recurrence=await import(recurrenceUrl);
const reminderSource=compile('lib/reminders.ts').replace("'./i18n'",JSON.stringify(i18nUrl)).replace("'./models'",JSON.stringify(modelsUrl)).replace("'./recurrence'",JSON.stringify(recurrenceUrl));
const reminders=await import('data:text/javascript;base64,'+Buffer.from(reminderSource).toString('base64'));
assert.equal(models.zonedToISO('2026-10-07T08:00','Europe/Berlin'),'2026-10-07T06:00:00.000Z');
assert.equal(models.zonedToISO('2026-12-07T08:00','Europe/Berlin'),'2026-12-07T07:00:00.000Z');
assert.equal(models.zonedToISO('2026-10-07T08:00','Europe/Kyiv'),'2026-10-07T05:00:00.000Z');
assert.throws(()=>models.zonedToISO('2026-03-29T02:30','Europe/Berlin'));
for(const value of ['2026-10-07T08:00','2026-10-25T01:30','2026-10-25T03:30','2026-12-07T08:00'])assert.equal(models.localDateInput(models.zonedToISO(value,'Europe/Berlin'),'Europe/Berlin'),value);
const now=new Date('2026-10-07T06:00:00Z');
const task={id:'task1',title:'Перевірити код',due_at:'2026-10-07T06:30:00Z',reminder_version:0};
assert.equal(reminders.needsDeadline(task,now),true);
assert.equal(reminders.needsDeadline({...task,due_at:'2026-10-07T06:30:01Z'},now),false);
assert.equal(reminders.needsDeadline({...task,due_at:'2026-10-07T06:00:00Z'},now),false);
assert.equal(reminders.localTime(now,'Europe/Berlin'),'08:00');
assert.equal(reminders.localTime(new Date('2026-12-07T07:00:00Z'),'Europe/Berlin'),'08:00');
assert.notEqual(reminders.deadlineJobKey(task),reminders.deadlineJobKey({...task,reminder_version:1}));
assert.ok(reminders.morningText([task],now,'Europe/Berlin').includes('Перевірити код'));
const entry={id:'repeat1',kind:'task',title:'Щоденне навчання',topic:'',blocks:[],status:'done',priority:'normal',dueAt:null,repeat:{days:[1,2,3,4,5,6,7],time:null},statusDate:'2026-10-07',occurrenceDate:null,createdAt:'2026-10-01',updatedAt:'2026-10-07'};
assert.equal(recurrence.projectEntry(entry,'Europe/Berlin',new Date('2026-10-07T21:59:00Z')).status,'done');
const tomorrow=recurrence.projectEntry(entry,'Europe/Berlin',new Date('2026-10-07T22:00:00Z'));
assert.equal(tomorrow.status,'todo');assert.equal(tomorrow.occurrenceDate,'2026-10-08');assert.equal(tomorrow.dueAt,null);
const weekly={...entry,repeat:{days:[1,3,5],time:'08:00'}};
assert.equal(recurrence.projectEntry(weekly,'Europe/Berlin',new Date('2026-10-10T12:00:00Z')).occurrenceDate,'2026-10-12');
assert.equal(recurrence.projectEntry(weekly,'Europe/Berlin',new Date('2026-10-10T12:00:00Z')).dueAt,'2026-10-12T06:00:00.000Z');
assert.equal(recurrence.nextOccurrence({days:[7],time:null},'2026-10-12'),'2026-10-18');
assert.equal(recurrence.repeatLabel(entry.repeat),'Щодня');
assert.equal(recurrence.repeatLabel(weekly.repeat),'Пн, Ср, Пт');
assert.equal(recurrence.recurringDeadline('2026-03-29','02:30','Europe/Berlin'),'2026-03-29T01:00:00.000Z');
assert.equal(recurrence.recurringDeadline('2026-10-25','08:00','Europe/Berlin'),'2026-10-25T07:00:00.000Z');
assert.equal(recurrence.recurringDeadline('2026-10-07','08:00','Europe/Kyiv'),'2026-10-07T05:00:00.000Z');
assert.equal(recurrence.projectEntry({...entry,statusDate:'2026-10-06'},'Europe/Berlin',now).status,'todo');
const nearMidnight=new Date('2026-10-07T21:45:00Z');
const midnightTask={...entry,repeat:{days:[1,2,3,4,5,6,7],time:'00:15'}};
const candidates=reminders.deadlineOccurrences(midnightTask,nearMidnight,'Europe/Berlin');
assert.equal(candidates.length,2);
const midnightReminder=candidates.filter(candidate=>candidate.status!=='done'&&reminders.needsDeadline({...task,due_at:candidate.dueAt},nearMidnight));
assert.equal(midnightReminder.length,1);assert.equal(midnightReminder[0].occurrenceDate,'2026-10-08');
assert.notEqual(reminders.deadlineJobKey({...task,due_at:recurrence.recurringDeadline('2026-10-08','08:00','Europe/Berlin')}),reminders.deadlineJobKey({...task,due_at:recurrence.recurringDeadline('2026-10-09','08:00','Europe/Berlin')}));
assert.ok(reminders.morningText([{...task,due_at:null}],now,'Europe/Berlin').includes('постійне завдання'));
console.log('Domain checks passed: weekly/daily recurrence, day-specific completion/reset, timezone/DST, reminder across midnight, deadline boundary and reminder versions.');

const i18n=await import(i18nUrl);
assert.equal(recurrence.repeatLabel(weekly.repeat,'en'),'Mon, Wed, Fri');
assert.equal(recurrence.repeatLabel(weekly.repeat,'de'),'Mo, Mi, Fr');
assert.equal(recurrence.repeatLabel(entry.repeat,'de'),'Jeden Tag');
assert.equal(i18n.countLabel(2,'entry','de'),'2 Einträge');
assert.equal(i18n.countLabel(1,'task','en'),'1 task');
assert.equal(i18n.countLabel(5,'task','uk'),'5 завдань');
for(const language of ['uk','en','de']){assert.ok(reminders.morningText([task],now,'Europe/Berlin',language).includes('Daymark'));assert.equal(models.dateLabel(null,'Europe/Berlin',language),i18n.translate(language,'Без дедлайну'));}
assert.ok(reminders.morningText([task],now,'Europe/Berlin','de').includes('Deine Aufgabenliste: 1'));
assert.ok(reminders.morningText([task],now,'Europe/Berlin','en').includes('Your task list: 1'));
console.log('Language checks passed: dates, weekday labels, count forms and Telegram summaries.');

// Exact deadline boundary and automatic status rules.
const fixed=new Date('2026-10-07T06:30:00Z');
assert.equal(models.deadlineStatus('progress',task.due_at,new Date(fixed.getTime()-1)),'progress');
assert.equal(models.deadlineStatus('progress',task.due_at,fixed),'overdue');
assert.equal(models.deadlineStatus('done',task.due_at,fixed),'done');
assert.equal(models.deadlineStatus('overdue',null,fixed),'todo');
assert.equal(models.deadlineStatus('overdue','2026-10-08T06:30:00Z',fixed),'todo');
assert.equal(reminders.needsOverdue(task,new Date(fixed.getTime()-1)),false);
assert.equal(reminders.needsOverdue(task,fixed),true);
assert.equal(reminders.needsOverdue({...task,due_at:null},fixed),false);
assert.notEqual(reminders.overdueJobKey(task),reminders.deadlineJobKey(task));
assert.notEqual(reminders.overdueJobKey(task),reminders.overdueJobKey({...task,reminder_version:1}));
const lateRecurring={...entry,status:'progress',statusDate:'2026-10-07',repeat:{days:[1,2,3,4,5,6,7],time:'08:30'}};
assert.equal(recurrence.projectEntry(lateRecurring,'Europe/Berlin',fixed).status,'overdue');
assert.equal(recurrence.projectEntry({...lateRecurring,status:'done'},'Europe/Berlin',fixed).status,'done');
assert.equal(recurrence.projectEntry({...lateRecurring,status:'overdue'},'Europe/Berlin',new Date('2026-10-07T22:00:00Z')).status,'todo');
assert.equal(reminders.overdueOccurrences(lateRecurring,new Date('2026-10-07T22:00:00Z'),'Europe/Berlin')[0].occurrenceDate,'2026-10-07');
assert.equal(reminders.overdueOccurrences({...lateRecurring,status:'done'},new Date('2026-10-07T22:00:00Z'),'Europe/Berlin').length,0);
assert.equal(reminders.overdueOccurrences({...lateRecurring,statusDate:'2026-10-08'},new Date('2026-10-07T22:00:00Z'),'Europe/Berlin').length,0);
assert.equal(reminders.overdueOccurrences({...lateRecurring,createdAt:'2026-10-08'},new Date('2026-10-07T22:00:00Z'),'Europe/Berlin').length,0);
assert.equal(reminders.overdueOccurrences({...lateRecurring,repeat:{days:[1,2,3,4,5,6,7],time:null}},fixed,'Europe/Berlin').length,0);
console.log('Overdue domain checks passed: exact boundary, completion, rescheduling, no deadline, recurrence reset and midnight recovery.');
