import { existsSync, readFileSync, writeFileSync, renameSync, mkdirSync } from 'node:fs';
import {resolve} from 'node:path';
import { setTimeout as pause } from 'node:timers/promises';
const {TELEGRAM_BOT_TOKEN,SITE_URL,SITES_ACCESS_TOKEN,TELEGRAM_SERVICE_SECRET}=process.env;
if(!TELEGRAM_BOT_TOKEN||!SITE_URL||!TELEGRAM_SERVICE_SECRET||!SITES_ACCESS_TOKEN)throw new Error('Set TELEGRAM_BOT_TOKEN, SITE_URL, SITES_ACCESS_TOKEN and TELEGRAM_SERVICE_SECRET in your private env file.');
const site=new URL(SITE_URL);if(site.protocol!=='https:' && !['localhost','127.0.0.1'].includes(site.hostname))throw new Error('HTTPS required.');
async function api(action,args={}){const res=await fetch(new URL('/api/service',site),{method:'POST',redirect:'error',headers:{'Content-Type':'application/json','Authorization':`Bearer ${TELEGRAM_SERVICE_SECRET}`,'OAI-Sites-Authorization':`Bearer ${SITES_ACCESS_TOKEN}`},body:JSON.stringify({action,...args}),signal:AbortSignal.timeout(30000)});if(!res.ok)throw new Error(`Site returned ${res.status}`);return res.json();}
async function bot(method,args={}){const res=await fetch(`https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/${method}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(args),signal:AbortSignal.timeout(35000)});let data;try{data=await res.json();}catch{throw new Error('Telegram response uncertain');}if(!data.ok){const error=new Error(`Telegram error ${data.error_code}`);error.definitive=true;throw error;}return data.result;}
const identity=await bot('getMe');const webhook=await bot('getWebhookInfo');if(webhook.url)throw new Error('This bot already uses a webhook. Use a dedicated bot or remove its webhook after checking the existing integration.');
const stateDir=resolve(process.env.TELEGRAM_STATE_DIR??'.telegram-state');mkdirSync(stateDir,{recursive:true,mode:0o700});const stateFile=resolve(stateDir,'offset.json');let offset=existsSync(stateFile)?JSON.parse(readFileSync(stateFile,'utf8')).offset:0;
function saveOffset(value){writeFileSync(stateFile+'.tmp',JSON.stringify({offset:value}),{mode:0o600});renameSync(stateFile+'.tmp',stateFile);offset=value;}
let running=true;process.on('SIGINT',()=>{running=false;});process.on('SIGTERM',()=>{running=false;});
async function reminders(){while(running){try{await api('heartbeat',{username:identity.username});const {jobs}=await api('tick');for(const job of jobs){let status='sent',error;try{await bot('sendMessage',{chat_id:job.chat_id,text:job.message});}catch(e){status=e.definitive?'failed':'unknown';error=e.message;}await api('ack',{id:job.id,status,error});}}catch{console.error('Reminder service unavailable; retrying on next tick.');}await pause(15000);}}
async function updates(){while(running){try{const batch=await bot('getUpdates',{offset,timeout:20,allowed_updates:['message']});for(const update of batch){const message=update.message;if(message?.chat?.type==='private'&&message.from?.id===message.chat.id){const match=/^\/start(?:@\w+)? ([a-f0-9]{48})$/.exec(message.text??'');if(match){const result=await api('confirm',{code:match[1],chatId:String(message.chat.id),name:message.from.first_name??message.from.username??'Telegram'});await bot('sendMessage',{chat_id:message.chat.id,text:result.message??'Відкрийте нове посилання на сайті.'});}else if(/^\/start/.test(message.text??'')){await bot('sendMessage',{chat_id:message.chat.id,text:'Фокус · Відкрийте налаштування сайту та натисніть «Підключити Telegram».'});}}saveOffset(update.update_id+1);}}catch{console.error('Bot polling unavailable; retrying.');await pause(5000);}}}
console.log(`Telegram companion started for @${identity.username}.`);
await Promise.all([reminders(),updates()]);
